seed: 42
test_size: &test_size 0.33

##################################################
# Parameters to download the dataset
##################################################
download_dataset:
  save_raw_data_path: data/raw

##################################################
# Parameters for data processing
##################################################
preprocessing:
  raw_data_path: "data/raw/"
  processed_data_path: &processed_data_path "data/processed/"
  target_sr: 8000

create_respresentations:
  input_data_path: *processed_data_path
  representation_data_path: &representation_data_path "data/spectrograms/"

extract_features:
  audio_input_data_path: *processed_data_path
  representation_data_path: *representation_data_path
  extracted_features_data_path: "data/features/"
  target_sr: 8000

##################################################
# Parameters for training
##################################################
training:
  processed_data_path: "data/processed"
  model_save_path: "models/model.pkl"
  test_size: *test_size

evaluation:
  load_model_path: "models/model.pkl"
  input_data_path: *processed_data_path

  test_size: *test_size
