seed: 42
test_size: &test_size 0.33
target_sr: &target_sr 8000

#####################################################################################################
#
# Parameters to download the dataset
#
#####################################################################################################
download_dataset:
  save_raw_data_path: data/raw

#####################################################################################################
#
# Parameters for data processing
#
#####################################################################################################
preprocessing:
  raw_data_path: "data/raw/"
  n_process: 10

  
  # FFT pipeline
  resampling_method: fft
  preprocessed_data_path: &processed_data_path "data/preprocessed_fft/"
  vect_size: 8000


  # #Downsampling pipeline
  # resampling_method: downsampling
  # preprocessed_data_path: &processed_data_path "data/preprocessed_downsampling/"
  # target_sr: *target_sr
  # vect_size: 8000
  


#####################################################################################################
#
# Parameters for features extraction
#
#####################################################################################################

features_extraction:
  ##############################################################################
  # Parameters to extract Chroma features using Short Time Fourier Transform
  ##############################################################################

  #processed_data_path: *processed_data_path
  #n_processes: 1
  #save_path: data/extracted_features/chroma_stft
  #algorithm:
  #  name: chroma_stft
  #  args:
  #    n_fft: 2048
  #    hop_length: 512

  ##############################################################################
  # Parameters to extract features using Root Mean Square
  ##############################################################################

  #processed_data_path: *processed_data_path
  #save_path: data/extracted_features/root_mean_square
  #n_processes: 10
  #algorithm:
  #  name: root_mean_square
  #  args:
  #    frame_length: 2048
  #    hop_length: 512

  ##############################################################################
  # Parameters to extract features using MFCC
  ##############################################################################

  #processed_data_path: *processed_data_path
  #n_processes: 10
  #save_path: data/extracted_features/mfcc
  #algorithm:
  #  name: mfcc
  #  args:
  #    n_mfcc: 20
  #    dct_type: 2

  ##############################################################################
  # Parameters to generate spectrograms
  ##############################################################################

  #processed_data_path: *processed_data_path
  #n_processes: 10
  #save_path: data/extracted_features/spectrogram
  #algorithm:
  #  name: spectrogram
  #  args:
  #    n_fft: 2048
  #    hop_length: 512

  ##############################################################################
  # Parameters to extract features using spectrogram centroid
  ##############################################################################

  #processed_data_path: *processed_data_path
  #n_processes: 10
  #save_path: data/extracted_features/spectrogram_centroid
  #algorithm:
  #  name: spectrogram_centroid
  #  args:
  #    n_fft: 2048
  #    hop_length: 512
  #    sr: *target_sr

  ##############################################################################
  # Parameters to extract features using spectrogram bandwith
  ##############################################################################

  #processed_data_path: *processed_data_path
  #n_processes: 10
  #save_path: data/extracted_features/spectrogram_bandwith
  #algorithm:
  #  name: spectrogram_bandwith
  #  args:
  #    n_fft: 2048
  #    hop_length: 512
  #    sr: *target_sr

  ##############################################################################
  # Parameters to extract features using spectrogram flatness
  ##############################################################################

  #processed_data_path: *processed_data_path
  #n_processes: 10
  #save_path: data/extracted_features/spectrogram_flatness
  #algorithm:
  #  name: spectrogram_flatness
  #  args:
  #    n_fft: 2048
  #    hop_length: 512
  #    sr: *target_sr

  ##############################################################################
  # Parameters to extract features using spectrogram rolloff
  ##############################################################################

  processed_data_path: *processed_data_path
  n_processes: 10
  save_path: data/extracted_features/spectrogram_rolloff
  algorithm:
    name: spectrogram_rolloff
    args:
      n_fft: 2048
      hop_length: 512
      sr: *target_sr

#####################################################################################################
#
# Parameters for features based training:
#
#####################################################################################################
features_based_training:
  ##############################################################################
  # Parameters to train models with Random Forest
  ##############################################################################
  path_to_data: data/extracted_features/mfcc
  # path_to_data: data/extracted_features/chroma_stft
  # path_to_data: data/extracted_features/root_mean_square
  # path_to_data: data/extracted_features/spectrogram
  # path_to_data: data/extracted_features/spectrogram_centroid
  # path_to_data: data/extracted_features/spectrogram_bandwith
  # path_to_data: data/extracted_features/spectrogram_flatness
  # path_to_data: data/extracted_features/spectrogram_rolloff
  save_model_path: models/
  algorithm:
   name: random_forest
   args:
     n_estimators: 100
     n_jobs: -1

  ##############################################################################
  # Parameters to train models with AlexNet
  ##############################################################################
  # path_to_data: data/extracted_features/mfcc
  # #path_to_data: data/extracted_features/chroma_stft
  # #path_to_data: data/extracted_features/root_mean_square
  # #path_to_data: data/extracted_features/spectrogram
  # #path_to_data: data/extracted_features/spectrogram_centroid
  # #path_to_data: data/extracted_features/spectrogram_bandwith
  # #path_to_data: data/extracted_features/spectrogram_flatness
  # #path_to_data: data/extracted_features/spectrogram_rolloff
  # save_model_path: models/
  # algorithm:
  #   name: AlexNet
  #   args:
  #     input_size: [150, 150, 1]
  #     n_classes: 10
  #     epochs: 1
  #     test_size: 0.33
  #     validation_size: 0.2


deep_learning_based_training:
  # path_to_data: data/preprocessed
  path_to_data: data/scattering_preprocessed
  # path_to_data: data/extracted_features/mfcc
  # path_to_data: data/extracted_features/chroma_stft
  # path_to_data: data/extracted_features/root_mean_square
  # path_to_data: data/extracted_features/spectrogram
  # path_to_data: data/extracted_features/spectrogram_centroid
  # path_to_data: data/extracted_features/spectrogram_bandwith
  # path_to_data: data/extracted_features/spectrogram_flatness
  # path_to_data: data/extracted_features/spectrogram_rolloff
 
  # save_model_path: models/scattering_transform1d
  save_model_path: models/scattering_transform1d
  epochs: 25
  algorithm:
    # name: audionet
    # name: fast_cnn
    # name: audionet
    name: scattering_transform1d
    args:
      n_classes: 10
      sequence_length: 8000


