seed: 42
test_size: &test_size 0.33

##################################################
# Parameters to download the dataset
##################################################
download_dataset:
  save_raw_data_path: data/raw

##################################################
# Parameters for data processing
##################################################
preprocessing:
  raw_data_path: "data/raw/"
  processed_data_path: &processed_data_path "data/processed/"
  target_sr: 8000

create_respresentations:
  input_data_path: *processed_data_path
  representation_data_path: &representation_data_path "data/spectrograms/"

extract_features:
  audio_input_data_path: *processed_data_path
  representation_data_path: *representation_data_path
  extracted_features_data_path: "data/features/"
  target_sr: 8000

##################################################
# Parameters for training
##################################################
training:
  processed_data_path: *processed_data_path
  test_size: *test_size
  model_save_path: "models/"
  spectrogram_data_path: *representation_data_path
  spectrogram_rf_model_save_path: &spectrogram_rf_model_save_path "models/spectrogram_rf.pkl"
  spectrogram_rf_n_estimators: 120
  spectrogram_rf_min_samples_split: 8
  mfcc_data_path: &mfcc_data_path "data/features/mfcc"
  mfcc_rf_model_save_path: &mfcc_rf_model_save_path "models/mfcc_rf.pkl"
  mfcc_rf_n_estimators: 130
  mfcc_rf_min_samples_split: 4
  spectrogram_descriptors_data_path: &spectrogram_descriptors_data_path "data/features/spectrogramDescriptors"
  spectrogram_descriptors_rf_model_save_path: &spectrogram_descriptors_rf_model_save_path "models/spectrogram_descriptors_rf.pkl"
  spectrogram_descriptors_rf_n_estimators: 150
  spectrogram_descriptors_rf_min_samples_split: 4
  spectrogram_descriptors_rf_max_depth: 36

evaluation:
  input_data_path: *processed_data_path
  test_size: *test_size
  spectrogram_data_path: *representation_data_path
  spectrogram_rf_model_save_path: *spectrogram_rf_model_save_path
  mfcc_data_path: *mfcc_data_path
  mfcc_rf_model_save_path: *mfcc_rf_model_save_path
  spectrogram_descriptors_data_path: *spectrogram_descriptors_data_path
  spectrogram_descriptors_rf_model_save_path: *spectrogram_descriptors_rf_model_save_path
