seed: 42
test_size: &test_size 0.33

#####################################################################################################
#
# Parameters to download the dataset
#
#####################################################################################################
download_dataset:
  save_raw_data_path: data/raw





#####################################################################################################
#
# Parameters for data processing
#
#####################################################################################################
preprocessing:
  raw_data_path: "data/raw/"
  preprocessed_data_path: &processed_data_path "data/preprocessed/"
  target_sr: 8000




#####################################################################################################
#
# Parameters for features extraction
#
#####################################################################################################

features_extraction:
  ##############################################################################
  # Parameters to extract Chroma features using Short Time Fourier Transform 
  ##############################################################################
  
  # processed_data_path: *processed_data_path
  # n_processes: 1
  # save_path: data/extracted_features/chroma_stft
  # algorithm: 
  #   name: chroma_stft
  #   args:
  #     n_fft: 2048
  #     hop_length: 512


  ##############################################################################
  # Parameters to extract features using Root Mean Square
  ##############################################################################

  # processed_data_path: *processed_data_path
  # save_path: data/extracted_features/root_mean_square
  # n_processes: 1
  # algorithm: 
  #   name: root_mean_square
  #   args:
  #     frame_length: 2048
  #     hop_length: 512


  ##############################################################################
  # Parameters to extract features using MFCC
  ##############################################################################

  processed_data_path: *processed_data_path
  n_processes: 10
  save_path: data/extracted_features/mfcc
  algorithm: 
    name: mfcc
    args:
      n_mfcc: 20
      dct_type: 2





#####################################################################################################
#
# Parameters for features based training:
#
#####################################################################################################
features_based_training:
  # path_to_data: data/extracted_features/mfcc
  # path_to_data: data/extracted_features/chroma_stft
  path_to_data: data/extracted_features/root_mean_square
  save_model_path: models/test_model.pkl
  algorithm:
    name: random_forest
    args:
      n_estimators: 100



